// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authservice/v1/authservice.proto

package authservicev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{2}
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{6}
}

type MeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{7}
}

func (x *MeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MeResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *MeResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MeResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{8}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{9}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateUserResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      *bool                  `protobuf:"varint,1,opt,name=is_active,proto3,oneof" json:"is_active,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{13}
}

func (x *ListUsersRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUserInfo       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersResponse) GetUsers() []*AdminUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type AdminUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{15}
}

func (x *AdminUserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUserInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AdminUserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserRequest) Reset() {
	*x = ActivateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserRequest) ProtoMessage() {}

func (x *ActivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserRequest.ProtoReflect.Descriptor instead.
func (*ActivateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserResponse) Reset() {
	*x = ActivateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserResponse) ProtoMessage() {}

func (x *ActivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserResponse.ProtoReflect.Descriptor instead.
func (*ActivateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{18}
}

func (x *ActivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeactivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserRequest) Reset() {
	*x = DeactivateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserRequest) ProtoMessage() {}

func (x *DeactivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserRequest.ProtoReflect.Descriptor instead.
func (*DeactivateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{19}
}

func (x *DeactivateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserResponse) Reset() {
	*x = DeactivateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserResponse) ProtoMessage() {}

func (x *DeactivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserResponse.ProtoReflect.Descriptor instead.
func (*DeactivateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{20}
}

func (x *DeactivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{21}
}

func (x *RoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserRolesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{24}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{25}
}

func (x *ListRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignRoleBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=role_code,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleBody) Reset() {
	*x = AssignRoleBody{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleBody) ProtoMessage() {}

func (x *AssignRoleBody) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleBody.ProtoReflect.Descriptor instead.
func (*AssignRoleBody) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{26}
}

func (x *AssignRoleBody) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Assignment    *AssignRoleBody        `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{27}
}

func (x *AssignRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignRoleRequest) GetAssignment() *AssignRoleBody {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{28}
}

func (x *AssignRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleCode      string                 `protobuf:"bytes,2,opt,name=role_code,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{29}
}

func (x *RevokeRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevokeRoleRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type RevokeRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{30}
}

func (x *RevokeRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{31}
}

func (x *PermissionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PermissionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{32}
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{33}
}

func (x *ListPermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=role_code,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{34}
}

func (x *GetRolePermissionsRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type GetRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{35}
}

func (x *GetRolePermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AssignPermissionBody struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionCode string                 `protobuf:"bytes,1,opt,name=permission_code,proto3" json:"permission_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignPermissionBody) Reset() {
	*x = AssignPermissionBody{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionBody) ProtoMessage() {}

func (x *AssignPermissionBody) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionBody.ProtoReflect.Descriptor instead.
func (*AssignPermissionBody) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{36}
}

func (x *AssignPermissionBody) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

type AssignPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=role_code,proto3" json:"role_code,omitempty"`
	Assignment    *AssignPermissionBody  `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionRequest) Reset() {
	*x = AssignPermissionRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionRequest) ProtoMessage() {}

func (x *AssignPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{37}
}

func (x *AssignPermissionRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *AssignPermissionRequest) GetAssignment() *AssignPermissionBody {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type AssignPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionResponse) Reset() {
	*x = AssignPermissionResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionResponse) ProtoMessage() {}

func (x *AssignPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{38}
}

func (x *AssignPermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokePermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoleCode       string                 `protobuf:"bytes,1,opt,name=role_code,proto3" json:"role_code,omitempty"`
	PermissionCode string                 `protobuf:"bytes,2,opt,name=permission_code,proto3" json:"permission_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokePermissionRequest) Reset() {
	*x = RevokePermissionRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionRequest) ProtoMessage() {}

func (x *RevokePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionRequest.ProtoReflect.Descriptor instead.
func (*RevokePermissionRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{39}
}

func (x *RevokePermissionRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *RevokePermissionRequest) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

type RevokePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePermissionResponse) Reset() {
	*x = RevokePermissionResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermissionResponse) ProtoMessage() {}

func (x *RevokePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermissionResponse.ProtoReflect.Descriptor instead.
func (*RevokePermissionResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{40}
}

func (x *RevokePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreatePermissionBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionBody) Reset() {
	*x = CreatePermissionBody{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionBody) ProtoMessage() {}

func (x *CreatePermissionBody) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionBody.ProtoReflect.Descriptor instead.
func (*CreatePermissionBody) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{41}
}

func (x *CreatePermissionBody) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePermissionBody) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *CreatePermissionBody  `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{42}
}

func (x *CreatePermissionRequest) GetPermission() *CreatePermissionBody {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreateRoleBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleBody) Reset() {
	*x = CreateRoleBody{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleBody) ProtoMessage() {}

func (x *CreateRoleBody) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleBody.ProtoReflect.Descriptor instead.
func (*CreateRoleBody) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{43}
}

func (x *CreateRoleBody) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleBody) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleBody) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *CreateRoleBody        `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{44}
}

func (x *CreateRoleRequest) GetRole() *CreateRoleBody {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleCode      string                 `protobuf:"bytes,1,opt,name=role_code,proto3" json:"role_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{45}
}

func (x *DeleteRoleRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{46}
}

func (x *DeleteRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePermissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionCode string                 `protobuf:"bytes,1,opt,name=permission_code,proto3" json:"permission_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{47}
}

func (x *DeletePermissionRequest) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{48}
}

func (x *DeletePermissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_authservice_v1_authservice_proto protoreflect.FileDescriptor

const file_authservice_v1_authservice_proto_rawDesc = "" +
	"\n" +
	" authservice/v1/authservice.proto\x12\x0eauthservice.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"a\n" +
	"\rLoginResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.authservice.v1.UserInfoR\x04user\"\x10\n" +
	"\x0eRefreshRequest\"c\n" +
	"\x0fRefreshResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.authservice.v1.UserInfoR\x04user\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\v\n" +
	"\tMeRequest\"\x88\x01\n" +
	"\n" +
	"MeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"R\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"[\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"n\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x87\x01\n" +
	"\x10ListUsersRequest\x12!\n" +
	"\tis_active\x18\x01 \x01(\bH\x00R\tis_active\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bper_page\x18\x04 \x01(\x05R\bper_pageB\f\n" +
	"\n" +
	"_is_active\"\x8e\x01\n" +
	"\x11ListUsersResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.authservice.v1.AdminUserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bper_page\x18\x04 \x01(\x05R\bper_page\"i\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13ActivateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14ActivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15DeactivateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeactivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"%\n" +
	"\x13GetUserRolesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x14GetUserRolesResponse\x12.\n" +
	"\x05roles\x18\x01 \x03(\v2\x18.authservice.v1.RoleInfoR\x05roles\"\x12\n" +
	"\x10ListRolesRequest\"C\n" +
	"\x11ListRolesResponse\x12.\n" +
	"\x05roles\x18\x01 \x03(\v2\x18.authservice.v1.RoleInfoR\x05roles\".\n" +
	"\x0eAssignRoleBody\x12\x1c\n" +
	"\trole_code\x18\x01 \x01(\tR\trole_code\"c\n" +
	"\x11AssignRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x1e.authservice.v1.AssignRoleBodyR\n" +
	"assignment\".\n" +
	"\x12AssignRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x11RevokeRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\trole_code\x18\x02 \x01(\tR\trole_code\".\n" +
	"\x12RevokeRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x18\n" +
	"\x16ListPermissionsRequest\"[\n" +
	"\x17ListPermissionsResponse\x12@\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1e.authservice.v1.PermissionInfoR\vpermissions\"9\n" +
	"\x19GetRolePermissionsRequest\x12\x1c\n" +
	"\trole_code\x18\x01 \x01(\tR\trole_code\"^\n" +
	"\x1aGetRolePermissionsResponse\x12@\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1e.authservice.v1.PermissionInfoR\vpermissions\"@\n" +
	"\x14AssignPermissionBody\x12(\n" +
	"\x0fpermission_code\x18\x01 \x01(\tR\x0fpermission_code\"}\n" +
	"\x17AssignPermissionRequest\x12\x1c\n" +
	"\trole_code\x18\x01 \x01(\tR\trole_code\x12D\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2$.authservice.v1.AssignPermissionBodyR\n" +
	"assignment\"4\n" +
	"\x18AssignPermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x17RevokePermissionRequest\x12\x1c\n" +
	"\trole_code\x18\x01 \x01(\tR\trole_code\x12(\n" +
	"\x0fpermission_code\x18\x02 \x01(\tR\x0fpermission_code\"4\n" +
	"\x18RevokePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"h\n" +
	"\x14CreatePermissionBody\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription:\x1a\x92A\x17\n" +
	"\x15\xd2\x01\x04code\xd2\x01\vdescription\"_\n" +
	"\x17CreatePermissionRequest\x12D\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2$.authservice.v1.CreatePermissionBodyR\n" +
	"permission\"Z\n" +
	"\x0eCreateRoleBody\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"G\n" +
	"\x11CreateRoleRequest\x122\n" +
	"\x04role\x18\x01 \x01(\v2\x1e.authservice.v1.CreateRoleBodyR\x04role\"1\n" +
	"\x11DeleteRoleRequest\x12\x1c\n" +
	"\trole_code\x18\x01 \x01(\tR\trole_code\".\n" +
	"\x12DeleteRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\x17DeletePermissionRequest\x12(\n" +
	"\x0fpermission_code\x18\x01 \x01(\tR\x0fpermission_code\"4\n" +
	"\x18DeletePermissionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xca(\n" +
	"\vAuthService\x12\x9c\x01\n" +
	"\x05Login\x12\x1c.authservice.v1.LoginRequest\x1a\x1d.authservice.v1.LoginResponse\"V\x92A6\n" +
	"\x04auth\x12\x05Login\x1a'Authenticate user by email and password\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12\xb6\x01\n" +
	"\aRefresh\x12\x1e.authservice.v1.RefreshRequest\x1a\x1f.authservice.v1.RefreshResponse\"j\x92AH\n" +
	"\x04auth\x12\x0fRefresh session\x1a/Rotate refresh token and issue new access token\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12\xe0\x01\n" +
	"\x06Logout\x12\x1d.authservice.v1.LogoutRequest\x1a\x1e.authservice.v1.LogoutResponse\"\x96\x01\x92Au\n" +
	"\x04auth\x12\x06Logout\x1aeEnds the current refresh session if present and clears its cookie. Succeeds even if no session exists\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12\x9e\x01\n" +
	"\x02Me\x12\x19.authservice.v1.MeRequest\x1a\x1a.authservice.v1.MeResponse\"a\x92AG\n" +
	"\x04auth\x12\fCurrent user\x1a#Get current authenticated user infob\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/auth/me\x12u\n" +
	"\aHealthz\x12\x1e.authservice.v1.HealthzRequest\x1a\x1f.authservice.v1.HealthzResponse\")\x92A\x16\n" +
	"\x06system\x12\fHealth check\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12\xc7\x01\n" +
	"\n" +
	"CreateUser\x12!.authservice.v1.CreateUserRequest\x1a\".authservice.v1.CreateUserResponse\"r\x92AQ\n" +
	"\x05users\x12\vCreate user\x1a-Create a new user with optional initial rolesb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/admin/users\x12\xdb\x01\n" +
	"\tListUsers\x12 .authservice.v1.ListUsersRequest\x1a!.authservice.v1.ListUsersResponse\"\x88\x01\x92Aj\n" +
	"\x05users\x12\n" +
	"List users\x1aGGet paginated list of users with optional filters by is_active and roleb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/admin/users\x12\xb3\x01\n" +
	"\aGetUser\x12\x1e.authservice.v1.GetUserRequest\x1a\x1d.authservice.v1.AdminUserInfo\"i\x92AF\n" +
	"\x05users\x12\x0eGet user by ID\x1a\x1fGet a single user by their UUIDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/admin/users/{id}\x12\xd2\x01\n" +
	"\fActivateUser\x12#.authservice.v1.ActivateUserRequest\x1a$.authservice.v1.ActivateUserResponse\"w\x92AK\n" +
	"\x05users\x12\rActivate user\x1a%Activate a user account by their UUIDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02#\"!/api/v1/admin/users/{id}/activate\x12\xf7\x01\n" +
	"\x0eDeactivateUser\x12%.authservice.v1.DeactivateUserRequest\x1a&.authservice.v1.DeactivateUserResponse\"\x95\x01\x92Ag\n" +
	"\x05users\x12\x0fDeactivate user\x1a?Deactivate a user account and revoke all their refresh sessionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02%\"#/api/v1/admin/users/{id}/deactivate\x12\xf2\x01\n" +
	"\fGetUserRoles\x12#.authservice.v1.GetUserRolesRequest\x1a$.authservice.v1.GetUserRolesResponse\"\x96\x01\x92Am\n" +
	"\x15user role assignments\x12\x0eGet user roles\x1a6Get the list of roles assigned to a user by their UUIDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/admin/users/{id}/roles\x12\xad\x01\n" +
	"\tListRoles\x12 .authservice.v1.ListRolesRequest\x1a!.authservice.v1.ListRolesResponse\"[\x92A=\n" +
	"\x05roles\x12\n" +
	"List roles\x1a\x1aGet the full list of rolesb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/admin/roles\x12\xc7\x01\n" +
	"\n" +
	"CreateRole\x12!.authservice.v1.CreateRoleRequest\x1a\x18.authservice.v1.RoleInfo\"|\x92AX\n" +
	"\x05roles\x12\vCreate role\x1a4Create a new role. Fails if role code already existsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x04role\"\x13/api/v1/admin/roles\x12\xf4\x01\n" +
	"\n" +
	"DeleteRole\x12!.authservice.v1.DeleteRoleRequest\x1a\".authservice.v1.DeleteRoleResponse\"\x9e\x01\x92At\n" +
	"\x05roles\x12\vDelete role\x1aPDelete a role by code. Fails if the role is assigned to users or has permissionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02!*\x1f/api/v1/admin/roles/{role_code}\x12\xb3\x02\n" +
	"\n" +
	"AssignRole\x12!.authservice.v1.AssignRoleRequest\x1a\".authservice.v1.AssignRoleResponse\"\xdd\x01\x92A\xa7\x01\n" +
	"\x15user role assignments\x12\x13Assign role to user\x1akAssign a role to a user by role code. Idempotent: assigning an already assigned role succeeds without errorb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02,:\n" +
	"assignment\"\x1e/api/v1/admin/users/{id}/roles\x12\xa4\x02\n" +
	"\n" +
	"RevokeRole\x12!.authservice.v1.RevokeRoleRequest\x1a\".authservice.v1.RevokeRoleResponse\"\xce\x01\x92A\x98\x01\n" +
	"\x15user role assignments\x12\x15Revoke role from user\x1aZRevoke a role from a user. Fails if the role is not assigned or it is the user's last roleb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02,**/api/v1/admin/users/{id}/roles/{role_code}\x12\xd7\x01\n" +
	"\x0fListPermissions\x12&.authservice.v1.ListPermissionsRequest\x1a'.authservice.v1.ListPermissionsResponse\"s\x92AO\n" +
	"\vpermissions\x12\x10List permissions\x1a Get the full list of permissionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/admin/permissions\x12\xa1\x02\n" +
	"\x12GetRolePermissions\x12).authservice.v1.GetRolePermissionsRequest\x1a*.authservice.v1.GetRolePermissionsResponse\"\xb3\x01\x92A}\n" +
	"\x1brole permission assignments\x12\x14Get role permissions\x1a:Get the list of permissions assigned to a role by its codeb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02-\x12+/api/v1/admin/roles/{role_code}/permissions\x12\xf0\x02\n" +
	"\x10AssignPermission\x12'.authservice.v1.AssignPermissionRequest\x1a(.authservice.v1.AssignPermissionResponse\"\x88\x02\x92A\xc5\x01\n" +
	"\x1brole permission assignments\x12\x19Assign permission to role\x1a}Assign a permission to a role by permission code. Idempotent: assigning an already assigned permission succeeds without errorb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x029:\n" +
	"assignment\"+/api/v1/admin/roles/{role_code}/permissions\x12\x97\x02\n" +
	"\x10CreatePermission\x12'.authservice.v1.CreatePermissionRequest\x1a\x1e.authservice.v1.PermissionInfo\"\xb9\x01\x92A\x88\x01\n" +
	"\vpermissions\x12\x11Create permission\x1aXCreate a new permission. Fails if permission code already exists or description is emptyb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02':\n" +
	"permission\"\x19/api/v1/admin/permissions\x12\x9a\x02\n" +
	"\x10DeletePermission\x12'.authservice.v1.DeletePermissionRequest\x1a(.authservice.v1.DeletePermissionResponse\"\xb2\x01\x92A|\n" +
	"\vpermissions\x12\x11Delete permission\x1aLDelete a permission by code. Fails if the permission is assigned to any roleb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02-*+/api/v1/admin/permissions/{permission_code}\x12\xcf\x02\n" +
	"\x10RevokePermission\x12'.authservice.v1.RevokePermissionRequest\x1a(.authservice.v1.RevokePermissionResponse\"\xe7\x01\x92A\x9e\x01\n" +
	"\x1brole permission assignments\x12\x1bRevoke permission from role\x1aTRevoke a permission from a role. Fails if the permission is not assigned to the roleb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02?*=/api/v1/admin/roles/{role_code}/permissions/{permission_code}B\x8e\x03\x92A\xbf\x02\x12T\n" +
	"\x10Auth Service API\x12;Authentication and authorization service for admin platform2\x031.02\x10application/json:\x10application/jsonZI\n" +
	"G\n" +
	"\x06Bearer\x12=\b\x02\x12(JWT access token. Format: Bearer {token}\x1a\rAuthorization \x02j\r\n" +
	"\vAuthServicej\x06\n" +
	"\x04authj\a\n" +
	"\x05usersj\x17\n" +
	"\x15user role assignmentsj\a\n" +
	"\x05rolesj\x1d\n" +
	"\x1brole permission assignmentsj\r\n" +
	"\vpermissionsj\b\n" +
	"\x06systemZIgithub.com/AlbinaKonovalova/auth-service/pkg/authservice/v1;authservicev1b\x06proto3"

var (
	file_authservice_v1_authservice_proto_rawDescOnce sync.Once
	file_authservice_v1_authservice_proto_rawDescData []byte
)

func file_authservice_v1_authservice_proto_rawDescGZIP() []byte {
	file_authservice_v1_authservice_proto_rawDescOnce.Do(func() {
		file_authservice_v1_authservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authservice_v1_authservice_proto_rawDesc), len(file_authservice_v1_authservice_proto_rawDesc)))
	})
	return file_authservice_v1_authservice_proto_rawDescData
}

var file_authservice_v1_authservice_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_authservice_v1_authservice_proto_goTypes = []any{
	(*LoginRequest)(nil),               // 0: authservice.v1.LoginRequest
	(*LoginResponse)(nil),              // 1: authservice.v1.LoginResponse
	(*RefreshRequest)(nil),             // 2: authservice.v1.RefreshRequest
	(*RefreshResponse)(nil),            // 3: authservice.v1.RefreshResponse
	(*LogoutRequest)(nil),              // 4: authservice.v1.LogoutRequest
	(*LogoutResponse)(nil),             // 5: authservice.v1.LogoutResponse
	(*MeRequest)(nil),                  // 6: authservice.v1.MeRequest
	(*MeResponse)(nil),                 // 7: authservice.v1.MeResponse
	(*HealthzRequest)(nil),             // 8: authservice.v1.HealthzRequest
	(*HealthzResponse)(nil),            // 9: authservice.v1.HealthzResponse
	(*UserInfo)(nil),                   // 10: authservice.v1.UserInfo
	(*CreateUserRequest)(nil),          // 11: authservice.v1.CreateUserRequest
	(*CreateUserResponse)(nil),         // 12: authservice.v1.CreateUserResponse
	(*ListUsersRequest)(nil),           // 13: authservice.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 14: authservice.v1.ListUsersResponse
	(*AdminUserInfo)(nil),              // 15: authservice.v1.AdminUserInfo
	(*GetUserRequest)(nil),             // 16: authservice.v1.GetUserRequest
	(*ActivateUserRequest)(nil),        // 17: authservice.v1.ActivateUserRequest
	(*ActivateUserResponse)(nil),       // 18: authservice.v1.ActivateUserResponse
	(*DeactivateUserRequest)(nil),      // 19: authservice.v1.DeactivateUserRequest
	(*DeactivateUserResponse)(nil),     // 20: authservice.v1.DeactivateUserResponse
	(*RoleInfo)(nil),                   // 21: authservice.v1.RoleInfo
	(*GetUserRolesRequest)(nil),        // 22: authservice.v1.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),       // 23: authservice.v1.GetUserRolesResponse
	(*ListRolesRequest)(nil),           // 24: authservice.v1.ListRolesRequest
	(*ListRolesResponse)(nil),          // 25: authservice.v1.ListRolesResponse
	(*AssignRoleBody)(nil),             // 26: authservice.v1.AssignRoleBody
	(*AssignRoleRequest)(nil),          // 27: authservice.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),         // 28: authservice.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),          // 29: authservice.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),         // 30: authservice.v1.RevokeRoleResponse
	(*PermissionInfo)(nil),             // 31: authservice.v1.PermissionInfo
	(*ListPermissionsRequest)(nil),     // 32: authservice.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),    // 33: authservice.v1.ListPermissionsResponse
	(*GetRolePermissionsRequest)(nil),  // 34: authservice.v1.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil), // 35: authservice.v1.GetRolePermissionsResponse
	(*AssignPermissionBody)(nil),       // 36: authservice.v1.AssignPermissionBody
	(*AssignPermissionRequest)(nil),    // 37: authservice.v1.AssignPermissionRequest
	(*AssignPermissionResponse)(nil),   // 38: authservice.v1.AssignPermissionResponse
	(*RevokePermissionRequest)(nil),    // 39: authservice.v1.RevokePermissionRequest
	(*RevokePermissionResponse)(nil),   // 40: authservice.v1.RevokePermissionResponse
	(*CreatePermissionBody)(nil),       // 41: authservice.v1.CreatePermissionBody
	(*CreatePermissionRequest)(nil),    // 42: authservice.v1.CreatePermissionRequest
	(*CreateRoleBody)(nil),             // 43: authservice.v1.CreateRoleBody
	(*CreateRoleRequest)(nil),          // 44: authservice.v1.CreateRoleRequest
	(*DeleteRoleRequest)(nil),          // 45: authservice.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),         // 46: authservice.v1.DeleteRoleResponse
	(*DeletePermissionRequest)(nil),    // 47: authservice.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),   // 48: authservice.v1.DeletePermissionResponse
}
var file_authservice_v1_authservice_proto_depIdxs = []int32{
	10, // 0: authservice.v1.LoginResponse.user:type_name -> authservice.v1.UserInfo
	10, // 1: authservice.v1.RefreshResponse.user:type_name -> authservice.v1.UserInfo
	15, // 2: authservice.v1.ListUsersResponse.users:type_name -> authservice.v1.AdminUserInfo
	21, // 3: authservice.v1.GetUserRolesResponse.roles:type_name -> authservice.v1.RoleInfo
	21, // 4: authservice.v1.ListRolesResponse.roles:type_name -> authservice.v1.RoleInfo
	26, // 5: authservice.v1.AssignRoleRequest.assignment:type_name -> authservice.v1.AssignRoleBody
	31, // 6: authservice.v1.ListPermissionsResponse.permissions:type_name -> authservice.v1.PermissionInfo
	31, // 7: authservice.v1.GetRolePermissionsResponse.permissions:type_name -> authservice.v1.PermissionInfo
	36, // 8: authservice.v1.AssignPermissionRequest.assignment:type_name -> authservice.v1.AssignPermissionBody
	41, // 9: authservice.v1.CreatePermissionRequest.permission:type_name -> authservice.v1.CreatePermissionBody
	43, // 10: authservice.v1.CreateRoleRequest.role:type_name -> authservice.v1.CreateRoleBody
	0,  // 11: authservice.v1.AuthService.Login:input_type -> authservice.v1.LoginRequest
	2,  // 12: authservice.v1.AuthService.Refresh:input_type -> authservice.v1.RefreshRequest
	4,  // 13: authservice.v1.AuthService.Logout:input_type -> authservice.v1.LogoutRequest
	6,  // 14: authservice.v1.AuthService.Me:input_type -> authservice.v1.MeRequest
	8,  // 15: authservice.v1.AuthService.Healthz:input_type -> authservice.v1.HealthzRequest
	11, // 16: authservice.v1.AuthService.CreateUser:input_type -> authservice.v1.CreateUserRequest
	13, // 17: authservice.v1.AuthService.ListUsers:input_type -> authservice.v1.ListUsersRequest
	16, // 18: authservice.v1.AuthService.GetUser:input_type -> authservice.v1.GetUserRequest
	17, // 19: authservice.v1.AuthService.ActivateUser:input_type -> authservice.v1.ActivateUserRequest
	19, // 20: authservice.v1.AuthService.DeactivateUser:input_type -> authservice.v1.DeactivateUserRequest
	22, // 21: authservice.v1.AuthService.GetUserRoles:input_type -> authservice.v1.GetUserRolesRequest
	24, // 22: authservice.v1.AuthService.ListRoles:input_type -> authservice.v1.ListRolesRequest
	44, // 23: authservice.v1.AuthService.CreateRole:input_type -> authservice.v1.CreateRoleRequest
	45, // 24: authservice.v1.AuthService.DeleteRole:input_type -> authservice.v1.DeleteRoleRequest
	27, // 25: authservice.v1.AuthService.AssignRole:input_type -> authservice.v1.AssignRoleRequest
	29, // 26: authservice.v1.AuthService.RevokeRole:input_type -> authservice.v1.RevokeRoleRequest
	32, // 27: authservice.v1.AuthService.ListPermissions:input_type -> authservice.v1.ListPermissionsRequest
	34, // 28: authservice.v1.AuthService.GetRolePermissions:input_type -> authservice.v1.GetRolePermissionsRequest
	37, // 29: authservice.v1.AuthService.AssignPermission:input_type -> authservice.v1.AssignPermissionRequest
	42, // 30: authservice.v1.AuthService.CreatePermission:input_type -> authservice.v1.CreatePermissionRequest
	47, // 31: authservice.v1.AuthService.DeletePermission:input_type -> authservice.v1.DeletePermissionRequest
	39, // 32: authservice.v1.AuthService.RevokePermission:input_type -> authservice.v1.RevokePermissionRequest
	1,  // 33: authservice.v1.AuthService.Login:output_type -> authservice.v1.LoginResponse
	3,  // 34: authservice.v1.AuthService.Refresh:output_type -> authservice.v1.RefreshResponse
	5,  // 35: authservice.v1.AuthService.Logout:output_type -> authservice.v1.LogoutResponse
	7,  // 36: authservice.v1.AuthService.Me:output_type -> authservice.v1.MeResponse
	9,  // 37: authservice.v1.AuthService.Healthz:output_type -> authservice.v1.HealthzResponse
	12, // 38: authservice.v1.AuthService.CreateUser:output_type -> authservice.v1.CreateUserResponse
	14, // 39: authservice.v1.AuthService.ListUsers:output_type -> authservice.v1.ListUsersResponse
	15, // 40: authservice.v1.AuthService.GetUser:output_type -> authservice.v1.AdminUserInfo
	18, // 41: authservice.v1.AuthService.ActivateUser:output_type -> authservice.v1.ActivateUserResponse
	20, // 42: authservice.v1.AuthService.DeactivateUser:output_type -> authservice.v1.DeactivateUserResponse
	23, // 43: authservice.v1.AuthService.GetUserRoles:output_type -> authservice.v1.GetUserRolesResponse
	25, // 44: authservice.v1.AuthService.ListRoles:output_type -> authservice.v1.ListRolesResponse
	21, // 45: authservice.v1.AuthService.CreateRole:output_type -> authservice.v1.RoleInfo
	46, // 46: authservice.v1.AuthService.DeleteRole:output_type -> authservice.v1.DeleteRoleResponse
	28, // 47: authservice.v1.AuthService.AssignRole:output_type -> authservice.v1.AssignRoleResponse
	30, // 48: authservice.v1.AuthService.RevokeRole:output_type -> authservice.v1.RevokeRoleResponse
	33, // 49: authservice.v1.AuthService.ListPermissions:output_type -> authservice.v1.ListPermissionsResponse
	35, // 50: authservice.v1.AuthService.GetRolePermissions:output_type -> authservice.v1.GetRolePermissionsResponse
	38, // 51: authservice.v1.AuthService.AssignPermission:output_type -> authservice.v1.AssignPermissionResponse
	31, // 52: authservice.v1.AuthService.CreatePermission:output_type -> authservice.v1.PermissionInfo
	48, // 53: authservice.v1.AuthService.DeletePermission:output_type -> authservice.v1.DeletePermissionResponse
	40, // 54: authservice.v1.AuthService.RevokePermission:output_type -> authservice.v1.RevokePermissionResponse
	33, // [33:55] is the sub-list for method output_type
	11, // [11:33] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_authservice_v1_authservice_proto_init() }
func file_authservice_v1_authservice_proto_init() {
	if File_authservice_v1_authservice_proto != nil {
		return
	}
	file_authservice_v1_authservice_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authservice_v1_authservice_proto_rawDesc), len(file_authservice_v1_authservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authservice_v1_authservice_proto_goTypes,
		DependencyIndexes: file_authservice_v1_authservice_proto_depIdxs,
		MessageInfos:      file_authservice_v1_authservice_proto_msgTypes,
	}.Build()
	File_authservice_v1_authservice_proto = out.File
	file_authservice_v1_authservice_proto_goTypes = nil
	file_authservice_v1_authservice_proto_depIdxs = nil
}
