// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authservice/v1/authservice.proto

package authservicev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{2}
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{6}
}

type MeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{7}
}

func (x *MeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MeResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *MeResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MeResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{8}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{9}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateUserResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      *bool                  `protobuf:"varint,1,opt,name=is_active,proto3,oneof" json:"is_active,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{13}
}

func (x *ListUsersRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUserInfo       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersResponse) GetUsers() []*AdminUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type AdminUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,proto3" json:"is_active,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{15}
}

func (x *AdminUserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUserInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AdminUserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserRequest) Reset() {
	*x = ActivateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserRequest) ProtoMessage() {}

func (x *ActivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserRequest.ProtoReflect.Descriptor instead.
func (*ActivateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateUserResponse) Reset() {
	*x = ActivateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateUserResponse) ProtoMessage() {}

func (x *ActivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateUserResponse.ProtoReflect.Descriptor instead.
func (*ActivateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{18}
}

func (x *ActivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeactivateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserRequest) Reset() {
	*x = DeactivateUserRequest{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserRequest) ProtoMessage() {}

func (x *DeactivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserRequest.ProtoReflect.Descriptor instead.
func (*DeactivateUserRequest) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{19}
}

func (x *DeactivateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserResponse) Reset() {
	*x = DeactivateUserResponse{}
	mi := &file_authservice_v1_authservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserResponse) ProtoMessage() {}

func (x *DeactivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authservice_v1_authservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserResponse.ProtoReflect.Descriptor instead.
func (*DeactivateUserResponse) Descriptor() ([]byte, []int) {
	return file_authservice_v1_authservice_proto_rawDescGZIP(), []int{20}
}

func (x *DeactivateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_authservice_v1_authservice_proto protoreflect.FileDescriptor

const file_authservice_v1_authservice_proto_rawDesc = "" +
	"\n" +
	" authservice/v1/authservice.proto\x12\x0eauthservice.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"a\n" +
	"\rLoginResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.authservice.v1.UserInfoR\x04user\"\x10\n" +
	"\x0eRefreshRequest\"c\n" +
	"\x0fRefreshResponse\x12\"\n" +
	"\faccess_token\x18\x01 \x01(\tR\faccess_token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.authservice.v1.UserInfoR\x04user\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\v\n" +
	"\tMeRequest\"\x88\x01\n" +
	"\n" +
	"MeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"R\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"[\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"n\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x87\x01\n" +
	"\x10ListUsersRequest\x12!\n" +
	"\tis_active\x18\x01 \x01(\bH\x00R\tis_active\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bper_page\x18\x04 \x01(\x05R\bper_pageB\f\n" +
	"\n" +
	"_is_active\"\x8e\x01\n" +
	"\x11ListUsersResponse\x123\n" +
	"\x05users\x18\x01 \x03(\v2\x1d.authservice.v1.AdminUserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\bper_page\x18\x04 \x01(\x05R\bper_page\"i\n" +
	"\rAdminUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1c\n" +
	"\tis_active\x18\x03 \x01(\bR\tis_active\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13ActivateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14ActivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15DeactivateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeactivateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8d\x0f\n" +
	"\vAuthService\x12\x9c\x01\n" +
	"\x05Login\x12\x1c.authservice.v1.LoginRequest\x1a\x1d.authservice.v1.LoginResponse\"V\x92A6\n" +
	"\x04auth\x12\x05Login\x1a'Authenticate user by email and password\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12\xb6\x01\n" +
	"\aRefresh\x12\x1e.authservice.v1.RefreshRequest\x1a\x1f.authservice.v1.RefreshResponse\"j\x92AH\n" +
	"\x04auth\x12\x0fRefresh session\x1a/Rotate refresh token and issue new access token\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refresh\x12\xe0\x01\n" +
	"\x06Logout\x12\x1d.authservice.v1.LogoutRequest\x1a\x1e.authservice.v1.LogoutResponse\"\x96\x01\x92Au\n" +
	"\x04auth\x12\x06Logout\x1aeEnds the current refresh session if present and clears its cookie. Succeeds even if no session exists\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12\x9e\x01\n" +
	"\x02Me\x12\x19.authservice.v1.MeRequest\x1a\x1a.authservice.v1.MeResponse\"a\x92AG\n" +
	"\x04auth\x12\fCurrent user\x1a#Get current authenticated user infob\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/auth/me\x12u\n" +
	"\aHealthz\x12\x1e.authservice.v1.HealthzRequest\x1a\x1f.authservice.v1.HealthzResponse\")\x92A\x16\n" +
	"\x06system\x12\fHealth check\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12\xc7\x01\n" +
	"\n" +
	"CreateUser\x12!.authservice.v1.CreateUserRequest\x1a\".authservice.v1.CreateUserResponse\"r\x92AQ\n" +
	"\x05admin\x12\vCreate user\x1a-Create a new user with optional initial rolesb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/admin/users\x12\xdb\x01\n" +
	"\tListUsers\x12 .authservice.v1.ListUsersRequest\x1a!.authservice.v1.ListUsersResponse\"\x88\x01\x92Aj\n" +
	"\x05admin\x12\n" +
	"List users\x1aGGet paginated list of users with optional filters by is_active and roleb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/admin/users\x12\xb3\x01\n" +
	"\aGetUser\x12\x1e.authservice.v1.GetUserRequest\x1a\x1d.authservice.v1.AdminUserInfo\"i\x92AF\n" +
	"\x05admin\x12\x0eGet user by ID\x1a\x1fGet a single user by their UUIDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/admin/users/{id}\x12\xd2\x01\n" +
	"\fActivateUser\x12#.authservice.v1.ActivateUserRequest\x1a$.authservice.v1.ActivateUserResponse\"w\x92AK\n" +
	"\x05admin\x12\rActivate user\x1a%Activate a user account by their UUIDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02#\"!/api/v1/admin/users/{id}/activate\x12\xf7\x01\n" +
	"\x0eDeactivateUser\x12%.authservice.v1.DeactivateUserRequest\x1a&.authservice.v1.DeactivateUserResponse\"\x95\x01\x92Ag\n" +
	"\x05admin\x12\x0fDeactivate user\x1a?Deactivate a user account and revoke all their refresh sessionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02%\"#/api/v1/admin/users/{id}/deactivateB\x94\x02\x92A\xc5\x01\x12T\n" +
	"\x10Auth Service API\x12;Authentication and authorization service for admin platform2\x031.02\x10application/json:\x10application/jsonZI\n" +
	"G\n" +
	"\x06Bearer\x12=\b\x02\x12(JWT access token. Format: Bearer {token}\x1a\rAuthorization \x02ZIgithub.com/AlbinaKonovalova/auth-service/pkg/authservice/v1;authservicev1b\x06proto3"

var (
	file_authservice_v1_authservice_proto_rawDescOnce sync.Once
	file_authservice_v1_authservice_proto_rawDescData []byte
)

func file_authservice_v1_authservice_proto_rawDescGZIP() []byte {
	file_authservice_v1_authservice_proto_rawDescOnce.Do(func() {
		file_authservice_v1_authservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authservice_v1_authservice_proto_rawDesc), len(file_authservice_v1_authservice_proto_rawDesc)))
	})
	return file_authservice_v1_authservice_proto_rawDescData
}

var file_authservice_v1_authservice_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_authservice_v1_authservice_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: authservice.v1.LoginRequest
	(*LoginResponse)(nil),          // 1: authservice.v1.LoginResponse
	(*RefreshRequest)(nil),         // 2: authservice.v1.RefreshRequest
	(*RefreshResponse)(nil),        // 3: authservice.v1.RefreshResponse
	(*LogoutRequest)(nil),          // 4: authservice.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 5: authservice.v1.LogoutResponse
	(*MeRequest)(nil),              // 6: authservice.v1.MeRequest
	(*MeResponse)(nil),             // 7: authservice.v1.MeResponse
	(*HealthzRequest)(nil),         // 8: authservice.v1.HealthzRequest
	(*HealthzResponse)(nil),        // 9: authservice.v1.HealthzResponse
	(*UserInfo)(nil),               // 10: authservice.v1.UserInfo
	(*CreateUserRequest)(nil),      // 11: authservice.v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 12: authservice.v1.CreateUserResponse
	(*ListUsersRequest)(nil),       // 13: authservice.v1.ListUsersRequest
	(*ListUsersResponse)(nil),      // 14: authservice.v1.ListUsersResponse
	(*AdminUserInfo)(nil),          // 15: authservice.v1.AdminUserInfo
	(*GetUserRequest)(nil),         // 16: authservice.v1.GetUserRequest
	(*ActivateUserRequest)(nil),    // 17: authservice.v1.ActivateUserRequest
	(*ActivateUserResponse)(nil),   // 18: authservice.v1.ActivateUserResponse
	(*DeactivateUserRequest)(nil),  // 19: authservice.v1.DeactivateUserRequest
	(*DeactivateUserResponse)(nil), // 20: authservice.v1.DeactivateUserResponse
}
var file_authservice_v1_authservice_proto_depIdxs = []int32{
	10, // 0: authservice.v1.LoginResponse.user:type_name -> authservice.v1.UserInfo
	10, // 1: authservice.v1.RefreshResponse.user:type_name -> authservice.v1.UserInfo
	15, // 2: authservice.v1.ListUsersResponse.users:type_name -> authservice.v1.AdminUserInfo
	0,  // 3: authservice.v1.AuthService.Login:input_type -> authservice.v1.LoginRequest
	2,  // 4: authservice.v1.AuthService.Refresh:input_type -> authservice.v1.RefreshRequest
	4,  // 5: authservice.v1.AuthService.Logout:input_type -> authservice.v1.LogoutRequest
	6,  // 6: authservice.v1.AuthService.Me:input_type -> authservice.v1.MeRequest
	8,  // 7: authservice.v1.AuthService.Healthz:input_type -> authservice.v1.HealthzRequest
	11, // 8: authservice.v1.AuthService.CreateUser:input_type -> authservice.v1.CreateUserRequest
	13, // 9: authservice.v1.AuthService.ListUsers:input_type -> authservice.v1.ListUsersRequest
	16, // 10: authservice.v1.AuthService.GetUser:input_type -> authservice.v1.GetUserRequest
	17, // 11: authservice.v1.AuthService.ActivateUser:input_type -> authservice.v1.ActivateUserRequest
	19, // 12: authservice.v1.AuthService.DeactivateUser:input_type -> authservice.v1.DeactivateUserRequest
	1,  // 13: authservice.v1.AuthService.Login:output_type -> authservice.v1.LoginResponse
	3,  // 14: authservice.v1.AuthService.Refresh:output_type -> authservice.v1.RefreshResponse
	5,  // 15: authservice.v1.AuthService.Logout:output_type -> authservice.v1.LogoutResponse
	7,  // 16: authservice.v1.AuthService.Me:output_type -> authservice.v1.MeResponse
	9,  // 17: authservice.v1.AuthService.Healthz:output_type -> authservice.v1.HealthzResponse
	12, // 18: authservice.v1.AuthService.CreateUser:output_type -> authservice.v1.CreateUserResponse
	14, // 19: authservice.v1.AuthService.ListUsers:output_type -> authservice.v1.ListUsersResponse
	15, // 20: authservice.v1.AuthService.GetUser:output_type -> authservice.v1.AdminUserInfo
	18, // 21: authservice.v1.AuthService.ActivateUser:output_type -> authservice.v1.ActivateUserResponse
	20, // 22: authservice.v1.AuthService.DeactivateUser:output_type -> authservice.v1.DeactivateUserResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_authservice_v1_authservice_proto_init() }
func file_authservice_v1_authservice_proto_init() {
	if File_authservice_v1_authservice_proto != nil {
		return
	}
	file_authservice_v1_authservice_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authservice_v1_authservice_proto_rawDesc), len(file_authservice_v1_authservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authservice_v1_authservice_proto_goTypes,
		DependencyIndexes: file_authservice_v1_authservice_proto_depIdxs,
		MessageInfos:      file_authservice_v1_authservice_proto_msgTypes,
	}.Build()
	File_authservice_v1_authservice_proto = out.File
	file_authservice_v1_authservice_proto_goTypes = nil
	file_authservice_v1_authservice_proto_depIdxs = nil
}
